# Globally-Fitting (with Replicas) Experimental Data as Supervised Learning

## (1): Import Libraries:

In [1]:
import datetime
import gc
import sys
import os

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.model_selection import train_test_split

# Replica surrogate utilities (fit_scalers lives here)
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath("__file__")), '..', '..'))
from surrogate_model.replica_surrogate.replica_surrogate_lib import fit_scalers, ensemble_predict, build_replica_model

## (2): Matplotlib rcparams Configuration:

In [2]:
plt.rcParams.update({
    "text.usetex": True, "font.family": "serif",
})
plt.rcParams['xtick.direction'] = 'in'
plt.rcParams['xtick.major.size'] = 8.5
plt.rcParams['xtick.major.width'] = 0.5
plt.rcParams['xtick.minor.size'] = 2.5
plt.rcParams['xtick.minor.width'] = 0.5
plt.rcParams['xtick.minor.visible'] = True
plt.rcParams['xtick.top'] = True
plt.rcParams['ytick.direction'] = 'in'
plt.rcParams['ytick.major.size'] = 8.5
plt.rcParams['ytick.major.width'] = 0.5
plt.rcParams['ytick.minor.size'] = 2.5
plt.rcParams['ytick.minor.width'] = 0.5
plt.rcParams['ytick.minor.visible'] = True
plt.rcParams['ytick.right'] = True
plt.rcParams['savefig.dpi'] = 300

## (3): Loading Data:

### (3.1): Loading Main File:

In [3]:
test_dataframe = pd.read_csv('../data/burner_data.csv')

### (3.2): Loading in the supervised learning $(x, y)$ pairs:

In [4]:
x_data = test_dataframe[["t", "x_b", "q_squared", "phi"]]
y_data = test_dataframe[["unp_beam_unp_target_xsec", "unp_target_bsa"]]

### (3.3): Checking out the $x$ data:

In [5]:
x_data.head()

      t    x_b  q_squared       phi
0 -0.11  0.185       1.62 -2.214125
1 -0.11  0.185       1.62 -1.963495
2 -0.11  0.185       1.62 -1.708154
3 -0.11  0.185       1.62 -1.445482
4 -0.11  0.185       1.62 -1.182810

### (3.4): Checking out the $y$ data:

In [6]:
y_data.head()

   unp_beam_unp_target_xsec  unp_target_bsa
0                    6.8022       -0.069272
1                    4.7934       -0.202153
2                    3.4116       -0.162798
3                    2.5726       -0.228718
4                    1.6976       -0.213949

### (3.5): Splitting along training/validation/testing:

In [7]:
x_remaining, x_testing, y_remaining, y_testing = train_test_split(
    x_data, y_data,
    test_size = 0.1, shuffle = True)

x_training, x_validation, y_training, y_validation = train_test_split(
    x_remaining, y_remaining,
    test_size = 0.1, shuffle = True)

### (3.6): Fitting StandardScalers on training data only

In [8]:
# Fit scalers ONCE on training data only — never on validation or test sets.
# Both observables are standardized so that under unweighted MSE they
# contribute equally to the gradient (xsec is O(5), BSA is O(0.2), so
# without standardization the BSA head collapses to a near-trivial fit).
x_scaler, y_scaler = fit_scalers(x_training, y_training)

# Standardize all splits using training-set statistics only (no data leakage)
x_training_scaled   = x_scaler.transform(x_training)
x_validation_scaled = x_scaler.transform(x_validation)
x_testing_scaled    = x_scaler.transform(x_testing)
x_data_scaled       = x_scaler.transform(x_data)

y_training_scaled   = y_scaler.transform(y_training)
y_validation_scaled = y_scaler.transform(y_validation)
y_testing_scaled    = y_scaler.transform(y_testing)

print(f"[INFO]: x_scaler  mean_  = {x_scaler.mean_}")
print(f"[INFO]: x_scaler  scale_ = {x_scaler.scale_}")
print(f"[INFO]: y_scaler  mean_  = {y_scaler.mean_}")
print(f"[INFO]: y_scaler  scale_ = {y_scaler.scale_}")

[INFO]: x_scaler  mean_  = [-0.11        0.185       1.62       -0.16842427]
[INFO]: x_scaler  scale_ = [1.         1.         1.         1.32675845]
[INFO]: y_scaler  mean_  = [ 2.9095    -0.0082678]
[INFO]: y_scaler  scale_ = [2.02236268 0.17681366]

In [9]:
len(x_training)

14

In [10]:
len(x_validation)

2

In [11]:
len(x_testing)

2

## (4): Defining the DNN Model:

In [12]:
# Model factory moved to replica_surrogate_lib.build_replica_model

## (5): **The Main Part of the Program: Replica Method!**

In [ ]:
number_of_replicas = 100

all_histories = []

models = []

for index in range(number_of_replicas):
    replica_number = index + 1
    print(f"[INFO]: Now training replica #{replica_number}")

    replica_seed = replica_number
    tf.random.set_seed(replica_seed)
    np.random.seed(replica_seed)

    tf.keras.backend.clear_session()
    gc.collect()

    dnn_model = build_replica_model(replica_seed)

    # Train on standardized targets so both xsec and BSA contribute equally
    # to the unweighted MSE loss.
    dnn_model_history = dnn_model.fit(
        x_training_scaled, y_training_scaled,
        validation_data = (x_validation_scaled, y_validation_scaled),
        epochs = 1000, 
        # [NOTE]: BATCHSIZE really matters!
        # batch_size = len(x_training),
        batch_size = 8,
        callbacks = [
            tf.keras.callbacks.ReduceLROnPlateau(
                monitor = "val_loss", factor = 0.5, patience = 50, min_lr = 1e-6,
                verbose = 1),
            tf.keras.callbacks.EarlyStopping(
                monitor = "val_loss", patience = 100, restore_best_weights = True
            )
        ],
        verbose = 0)
    
    all_histories.append(dnn_model_history.history)

    model_testing_loss = dnn_model.evaluate(x_testing_scaled, y_testing_scaled, verbose = 0)
    print(f"[INFO]: Test loss for replica #{replica_number}: {model_testing_loss}")

    figure, axis = plt.subplots(1, 1, figsize = (6, 6))

    axis.plot(dnn_model_history.history['loss'], 
        label = "Training Loss", color = 'orange', alpha = 0.6)
    axis.plot(dnn_model_history.history['val_loss'], 
        label = "Validation Loss", color = 'purple', alpha = 0.6)

    axis.set_xlabel(r"Epoch", fontsize = 14.)
    axis.set_ylabel(r"Loss (standardized space)", fontsize = 14.)
    axis.set_title(
        rf"Surrogate Model (Testing = ${model_testing_loss:.3f}$)",
        fontsize = 14.)
    axis.legend(fontsize = 14.)
    axis.grid(visible = False)

    axis.text(
        0.00, -0.11,
        f"Figure rendered {datetime.datetime.now().strftime('%Y%m%d-%H%M%S')}", 
        transform = axis.transAxes, verticalalignment = 'top',  horizontalalignment = 'left', fontsize = 9.,)

    for extension in ['png', 'eps']:
        figure.savefig(
            fname = f"./plots/surrogate_lc_replica_{replica_number}_v13.{extension}",
            facecolor = 'white', transparent = False)

    plt.close(figure)

    del figure
    del axis

    # dnn_model.save(f"replica_{replica_number}_v13.keras")
    models.append(dnn_model)

# Ensemble predict on all data points in physical units
average_prediction, standard_dev_prediction = ensemble_predict(
    models, x_data, x_scaler, y_scaler
)

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #1

2026-05-26 22:47:33.569556: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz

Epoch 367: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 417: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #1: 0.13608410954475403

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #2

Epoch 380: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 430: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #2: 0.12501585483551025

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #3

Epoch 342: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 392: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #3: 0.10913459956645966

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #4

Epoch 369: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 419: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #4: 0.17711293697357178

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #5

Epoch 60: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 110: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #5: 0.1795114427804947

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #6

Epoch 366: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 416: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #6: 0.10324610769748688

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #7

Epoch 63: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 113: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #7: 0.1662822812795639

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #8

Epoch 372: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 422: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #8: 0.10258278250694275

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #9

Epoch 54: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 104: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #9: 0.23064124584197998

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #10

Epoch 64: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 114: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #10: 0.11101324111223221

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #11

Epoch 376: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 426: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #11: 0.09599041938781738

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #12

Epoch 395: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 445: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #12: 0.19191068410873413

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #13

Epoch 377: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 427: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #13: 0.10157904773950577

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #14

Epoch 71: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 121: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #14: 0.13058464229106903

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #15

Epoch 348: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 398: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #15: 0.14338737726211548

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #16

Epoch 383: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 433: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #16: 0.16812247037887573

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #17

Epoch 60: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 110: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #17: 0.1626289039850235

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #18

Epoch 367: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 417: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #18: 0.13491366803646088

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #19

Epoch 351: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 401: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #19: 0.11428087949752808

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #20

Epoch 283: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 333: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #20: 0.08883075416088104

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #21

Epoch 59: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 109: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #21: 0.22358158230781555

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #22

Epoch 387: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 437: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #22: 0.13175185024738312

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #23

Epoch 329: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 746: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.

Epoch 796: ReduceLROnPlateau reducing learning rate to 3.7500001781154424e-05.
[INFO]: Test loss for replica #23: 0.19140523672103882

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #24

Epoch 69: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 119: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #24: 0.11299613118171692

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #25

Epoch 63: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 113: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #25: 0.18996012210845947

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #26

Epoch 365: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 415: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #26: 0.1411600559949875

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #27

Epoch 392: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 442: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #27: 0.14561250805854797

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #28

Epoch 339: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 389: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #28: 0.1560295820236206

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #29

Epoch 441: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 491: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #29: 0.1987382173538208

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #30

Epoch 380: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 430: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #30: 0.1792747974395752

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #31

Epoch 334: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 384: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #31: 0.09719632565975189

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #32

Epoch 62: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 112: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #32: 0.12502621114253998

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #33

Epoch 310: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 360: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #33: 0.13747814297676086

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #34

Epoch 69: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 620: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.

Epoch 670: ReduceLROnPlateau reducing learning rate to 3.7500001781154424e-05.
[INFO]: Test loss for replica #34: 0.12800666689872742

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #35

Epoch 364: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 414: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #35: 0.1481310874223709

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #36

Epoch 364: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 414: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #36: 0.11687006056308746

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #37

Epoch 55: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 517: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.

Epoch 567: ReduceLROnPlateau reducing learning rate to 3.7500001781154424e-05.
[INFO]: Test loss for replica #37: 0.1306782066822052

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #38

Epoch 263: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 313: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #38: 0.06586886942386627

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #39

Epoch 366: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 416: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #39: 0.11849524080753326

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #40

Epoch 377: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 427: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #40: 0.15817567706108093

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #41

Epoch 353: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 403: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #41: 0.13851460814476013

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #42

Epoch 71: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 121: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #42: 0.08813640475273132

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #43

Epoch 364: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 414: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #43: 0.09821527451276779

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.

[INFO]: Now training replica #44

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

Epoch 66: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 116: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #44: 0.16439545154571533

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #45

Epoch 339: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 389: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #45: 0.1038186252117157

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #46

Epoch 354: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 404: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #46: 0.12607724964618683

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #47

Epoch 58: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 108: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #47: 0.1601296067237854

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #48

WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

Epoch 344: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 394: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #48: 0.12573988735675812

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #49

Epoch 346: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 396: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #49: 0.11309665441513062

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

[INFO]: Now training replica #50

WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.

Epoch 369: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.

Epoch 419: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
[INFO]: Test loss for replica #50: 0.12193544954061508

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.

1/1 [==============================] - 0s 36ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 60ms/step
1/1 [==============================] - 0s 20ms/step
WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x366f7d800> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x366f7d800> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 [==============================] - 0s 21ms/step
WARNING:tensorflow:6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x366f7f7e0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x366f7f7e0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 23ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 22ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 22ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 22ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 22ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 22ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 22ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 20ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 22ms/step
1/1 [==============================] - 0s 20ms/step

In [14]:
grouped = test_dataframe.groupby(['t', 'x_b', 'q_squared'])

In [15]:
# this is trento convention: -pi to pi:
phi_smooth = np.linspace(-np.pi, np.pi, 361)
special_phis = [0, np.pi/2, -np.pi/2, np.pi]

for (t_value, xb_value, qsquared_value), group in grouped:
    print(f"Processing t = {t_value}, xb = {xb_value}, Q2 = {qsquared_value}")

    group = group.sort_values('phi')

    xsec_err = group['unp_beam_unp_target_xsec_err'].values
    bsa_err = group['unp_target_bsa_err'].values

    indices = group.index.values

    # all_predictions already in physical units (inverse-transformed in the loop above)
    xsec_pred = average_prediction[indices, 0]
    bsa_pred = average_prediction[indices, 1]
    xsec_std = standard_dev_prediction[indices, 0]
    bsa_std = standard_dev_prediction[indices, 1]

    x_smooth = np.column_stack([
        np.full_like(phi_smooth, t_value),
        np.full_like(phi_smooth, xb_value),
        np.full_like(phi_smooth, qsquared_value),
        phi_smooth
    ])
    # Ensemble predict on smooth curve inputs (x_scaler applied inside)
    smooth_mean, smooth_std = ensemble_predict(models, x_smooth, x_scaler, y_scaler)

    xsec_smooth_mean = smooth_mean[:, 0]
    bsa_smooth_mean = smooth_mean[:, 1]

    xsec_smooth_std = smooth_std[:, 0]
    bsa_smooth_std = smooth_std[:, 1]

    for phi_target in special_phis:
        phi_index = np.argmin(np.abs(phi_smooth - phi_target))
        phi_actual = phi_smooth[phi_index]
        sigma_value = bsa_smooth_std[phi_index]
        print(
            f"[INFO]: "
            f"(xb = {xb_value:.3f}, "
            f"t = {t_value:.3f}, "
            f"Q2 = {qsquared_value:.3f}) "
            f"BSA 1σ uncertainty at "
            f"phi = {phi_actual:.3f} rad "
            f"is ±{sigma_value:.6f}"
        )

    phi = group['phi'].values
    xsec_actual = group['unp_beam_unp_target_xsec'].values
    bsa_actual = group['unp_target_bsa'].values

    xsec_res = xsec_actual - xsec_pred
    bsa_res = bsa_actual - bsa_pred

    chi2_xsec = np.sum(xsec_res**2) / len(phi)
    chi2_bsa = np.sum(bsa_res**2) / len(phi)

    residuals_figure, axes = plt.subplots(2, 2, figsize = (10, 8), sharex = 'col', layout = "tight")

    axes[1, 0].text(
        -0.1, -0.1, 
        fr"Figure rendered {datetime.datetime.now().strftime('%Y%m%d-%H%M%S')}", 
        transform = axes[1, 0].transAxes)

    axes[0, 0].plot(phi_smooth, xsec_smooth_mean, color = 'red', lw = 2, label = rf'Replica Average ($N = {number_of_replicas}$)')
    axes[0, 0].fill_between(
        phi_smooth, xsec_smooth_mean - xsec_smooth_std, xsec_smooth_mean + xsec_smooth_std,
        color = 'red', alpha = 0.3,
        label = r'$\sigma$ band'
    )
    axes[0, 0].errorbar(
        phi, xsec_actual, yerr = xsec_err, 
        fmt = 'o', mfc = 'white', mec = 'black', ms = 5, ecolor = 'black', elinewidth = 1, capsize = 2, alpha = 0.8,
        label = 'Experimental Data')
    axes[0, 0].set_ylabel(r"$d^{4}\sigma$", fontsize = 14)
    axes[0, 0].set_title(rf"Cross Section ($\chi^2_\nu = {chi2_xsec:.3f}$)")
    axes[0, 0].legend()
    axes[0, 0].grid(True, linestyle=':', alpha = 0.6)

    axes[0, 1].scatter(phi, xsec_res, color = 'blue', alpha = 0.6)
    axes[0, 1].axhline(0, color = 'black', linestyle = '--')
    axes[0, 1].set_title("Residuals")
    axes[0, 1].grid(True, linestyle = ':', alpha = 0.6)

    axes[1, 0].plot(phi_smooth, bsa_smooth_mean, color = 'green', lw = 2, label = rf'Replica Average ($N = {number_of_replicas}$)')
    axes[1, 0].fill_between(
        phi_smooth, bsa_smooth_mean - bsa_smooth_std, bsa_smooth_mean + bsa_smooth_std,
        color = 'green', alpha = 0.3,
        label = r'$\sigma$ band'
    )
    axes[1, 0].errorbar(
        phi, bsa_actual, yerr = bsa_err, 
        fmt = 'o', mfc = 'white', mec = 'black', ms = 5, ecolor = 'black', elinewidth = 1, capsize = 2, alpha = 0.8,
        label = 'Experimental Data')
    
    axes[1, 0].set_ylabel("BSA", fontsize = 14)
    axes[1, 0].set_xlabel(r"$\phi$ (radians)", fontsize = 14)
    axes[1, 0].set_title(rf"BSA ($\chi^2_\nu = {chi2_bsa:.3f}$)")
    axes[1, 0].legend()
    axes[1, 0].grid(True, linestyle = ':', alpha = 0.6)

    axes[1, 1].scatter(phi, bsa_res, color = 'purple', alpha = 0.6)
    axes[1, 1].axhline(0, color = 'black', linestyle = '--')
    axes[1, 1].set_xlabel(r"$\phi$ (radians)", fontsize = 14)
    axes[1, 1].set_title("Residuals")
    axes[1, 1].grid(True, linestyle = ':', alpha = 0.6)
    
    residuals_figure.suptitle(
        "Kinematic Setting:\n"
        rf"$t = {t_value:.3f}$, $x_\textrm{{B}} = {xb_value:.3f}$, $Q^2 = {qsquared_value:.3f}$",
        fontsize = 16
    )

    filename = f"./plots/t{t_value:.3f}_xb{xb_value:.3f}_q2{qsquared_value:.3f}_residuals_v13"
    for extension in ['png', 'eps']:
        residuals_figure.savefig(
            fname = f"{filename}.{extension}",
            facecolor = 'white', transparent = False)

    plt.close(residuals_figure)

Processing t = -0.11, xb = 0.185, Q2 = 1.62
12/12 [==============================] - 0s 309us/step
12/12 [==============================] - 0s 277us/step
12/12 [==============================] - 0s 294us/step
12/12 [==============================] - 0s 263us/step
12/12 [==============================] - 0s 269us/step
12/12 [==============================] - 0s 283us/step
12/12 [==============================] - 0s 278us/step
12/12 [==============================] - 0s 274us/step
 1/12 [=>............................] - ETA: 0s

/opt/anaconda3/envs/gpd_dnn/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

12/12 [==============================] - 0s 273us/step
12/12 [==============================] - 0s 289us/step
12/12 [==============================] - 0s 260us/step
12/12 [==============================] - 0s 264us/step
12/12 [==============================] - 0s 259us/step
12/12 [==============================] - 0s 304us/step
12/12 [==============================] - 0s 262us/step
12/12 [==============================] - 0s 274us/step
12/12 [==============================] - 0s 265us/step
12/12 [==============================] - 0s 275us/step
12/12 [==============================] - 0s 292us/step
12/12 [==============================] - 0s 264us/step
12/12 [==============================] - 0s 261us/step
12/12 [==============================] - 0s 258us/step
12/12 [==============================] - 0s 273us/step
12/12 [==============================] - 0s 267us/step
12/12 [==============================] - 0s 362us/step
12/12 [==============================] - 0s 325us/step
12/12 [==============================] - 0s 288us/step
12/12 [==============================] - 0s 284us/step
12/12 [==============================] - 0s 265us/step
12/12 [==============================] - 0s 306us/step
12/12 [==============================] - 0s 274us/step
12/12 [==============================] - 0s 259us/step
12/12 [==============================] - 0s 287us/step
12/12 [==============================] - 0s 269us/step
12/12 [==============================] - 0s 292us/step
12/12 [==============================] - 0s 264us/step
12/12 [==============================] - 0s 277us/step
12/12 [==============================] - 0s 267us/step
12/12 [==============================] - 0s 268us/step
12/12 [==============================] - 0s 268us/step
12/12 [==============================] - 0s 250us/step
12/12 [==============================] - 0s 263us/step
12/12 [==============================] - 0s 269us/step
12/12 [==============================] - 0s 264us/step
12/12 [==============================] - 0s 258us/step
12/12 [==============================] - 0s 268us/step
12/12 [==============================] - 0s 318us/step
12/12 [==============================] - 0s 275us/step
12/12 [==============================] - 0s 263us/step
12/12 [==============================] - 0s 263us/step
[INFO]: (xb = 0.185, t = -0.110, Q2 = 1.620) BSA 1σ uncertainty at phi = 0.000 rad is ±0.019174
[INFO]: (xb = 0.185, t = -0.110, Q2 = 1.620) BSA 1σ uncertainty at phi = 1.571 rad is ±0.038021
[INFO]: (xb = 0.185, t = -0.110, Q2 = 1.620) BSA 1σ uncertainty at phi = -1.571 rad is ±0.019329
[INFO]: (xb = 0.185, t = -0.110, Q2 = 1.620) BSA 1σ uncertainty at phi = 3.142 rad is ±0.020970

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.

In [16]:
xb_q2_groups = test_dataframe.groupby(['x_b', 'q_squared'])
n_xb_q2 = xb_q2_groups.ngroups
print(n_xb_q2)

1

In [17]:
phi_grid = np.linspace(-np.pi, np.pi, 361)

In [18]:
for (xb_value, qsquared_value), group in xb_q2_groups:

    group = group.sort_values(['t', 'phi'])

    t_values = np.sort(group['t'].unique())

    phi_meshgrid, t_meshgrid = np.meshgrid(phi_grid, t_values)

    phi_data = group['phi'].values
    t_data = group['t'].values

    indices = group.index.values

    # all_predictions already in physical units
    xsec_pred = average_prediction[indices, 0]
    bsa_pred = average_prediction[indices, 1]

    xsec_actual = group['unp_beam_unp_target_xsec'].values
    bsa_actual = group['unp_target_bsa'].values

    xsec_res = xsec_actual - xsec_pred
    bsa_res = bsa_actual - bsa_pred

    colors_xsec = np.where(xsec_res >= 0, 'red', 'blue')
    colors_bsa = np.where(bsa_res >= 0, 'red', 'blue')

    model_surface_input = np.column_stack([
        t_meshgrid.ravel(),
        np.full(t_meshgrid.size, xb_value),
        np.full(t_meshgrid.size, qsquared_value),
        phi_meshgrid.ravel()
    ])
    # Ensemble predict on surface inputs (x_scaler applied inside)
    surface_mean, surface_std_dev = ensemble_predict(
        models, model_surface_input, x_scaler, y_scaler
    )

    xsec_surface = surface_mean[:, 0].reshape(t_meshgrid.shape)
    bsa_surface = surface_mean[:, 1].reshape(t_meshgrid.shape)

    xsec_stddev_surface = surface_std_dev[:, 0].reshape(t_meshgrid.shape)
    bsa_stddev_surface = surface_std_dev[:, 1].reshape(t_meshgrid.shape)

    zero_plane_xsec = np.zeros_like(xsec_surface)
    zero_plane_bsa = np.zeros_like(bsa_surface)

    fig = plt.figure(figsize = (10, 10), layout = "tight")

    ax1 = fig.add_subplot(2, 2, 1, projection = '3d')
    ax2 = fig.add_subplot(2, 2, 2, projection = '3d')
    ax3 = fig.add_subplot(2, 2, 3, projection = '3d')
    ax4 = fig.add_subplot(2, 2, 4, projection = '3d')

    ax1.plot_surface(phi_meshgrid, t_meshgrid, xsec_surface, cmap = 'viridis', alpha = 0.5)
    ax1.plot_surface(phi_meshgrid, t_meshgrid, xsec_surface + xsec_stddev_surface, color = "red", alpha = 0.2)
    ax1.plot_surface(phi_meshgrid, t_meshgrid, xsec_surface - xsec_stddev_surface, color = "red", alpha = 0.2)
    ax1.scatter(phi_data, t_data, xsec_actual, facecolors = 'white', edgecolors = 'black', s = 20, linewidths = 0.5, alpha = 1.0)

    ax1.set_xlabel(r'$\phi$ (Radians)')
    ax1.set_ylabel(r'$t$')
    ax1.set_zlabel(r'$d^{4}\sigma^{UU}$')
    ax1.set_title('Cross Section', fontsize = 16)

    ax2.plot_surface(phi_meshgrid, t_meshgrid, zero_plane_xsec, color = 'gray', alpha = 0.15)
    ax2.scatter(phi_data, t_data, xsec_res, color = colors_xsec, s = 20)
 
    ax2.set_xlabel(r'$\phi$')
    ax2.set_ylabel(r'$t$')
    ax2.set_zlabel('Residuals')
    ax2.set_title('Cross Section Residuals', fontsize = 16)

    ax3.plot_surface(phi_meshgrid, t_meshgrid, bsa_surface, cmap='plasma', alpha = 0.5)
    ax3.plot_surface(phi_meshgrid, t_meshgrid, bsa_surface + bsa_stddev_surface, color = "red", alpha = 0.2)
    ax3.plot_surface(phi_meshgrid, t_meshgrid, bsa_surface - bsa_stddev_surface, color = "red", alpha = 0.2)
    ax3.scatter(phi_data, t_data, bsa_actual, facecolors = 'white', edgecolors = 'black', s = 20, linewidths = 0.5, alpha = 1.0)

    ax3.set_xlabel(r'$\phi$ (Radians)')
    ax3.set_ylabel(r'$t$')
    ax3.set_zlabel('BSA')
    ax3.set_title('BSA', fontsize = 16)

    ax4.plot_surface(phi_meshgrid, t_meshgrid, zero_plane_bsa, color = 'gray', alpha = 0.15)
    ax4.scatter(phi_data, t_data, bsa_res, color = colors_bsa, s = 20)

    ax4.set_xlabel(r'$\phi$')
    ax4.set_ylabel(r'$t$')
    ax4.set_zlabel('Residuals')
    ax4.set_title('BSA Residuals', fontsize = 16)

    fig.suptitle(
        r"DNN Interpolations Across $t$ and $\phi$"
        "\n"
        rf"Kinematic Setting: $x_\textrm{{B}} = {xb_value:.4g}$, $Q^2 = {qsquared_value:.4g}$",
        fontsize = 16)

    plot_filename = f"./plots/surface_xb{xb_value:.4g}_q2{qsquared_value:.4g}_v13"
    
    for extension in ['png', 'eps']:
        fig.savefig(f"{plot_filename}.{extension}", facecolor = 'white')

    plt.close(fig)

    # cleanup:
    del fig
    del ax1
    del ax2
    del ax3
    del ax4

12/12 [==============================] - 0s 410us/step
12/12 [==============================] - 0s 295us/step
12/12 [==============================] - 0s 291us/step
12/12 [==============================] - 0s 279us/step
12/12 [==============================] - 0s 269us/step
12/12 [==============================] - 0s 307us/step
12/12 [==============================] - 0s 264us/step

/opt/anaconda3/envs/gpd_dnn/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

12/12 [==============================] - 0s 321us/step
12/12 [==============================] - 0s 288us/step
12/12 [==============================] - 0s 275us/step
12/12 [==============================] - 0s 278us/step
12/12 [==============================] - 0s 265us/step
12/12 [==============================] - 0s 338us/step
12/12 [==============================] - 0s 276us/step
12/12 [==============================] - 0s 344us/step
12/12 [==============================] - 0s 276us/step
12/12 [==============================] - 0s 364us/step
12/12 [==============================] - 0s 268us/step
12/12 [==============================] - 0s 361us/step
12/12 [==============================] - 0s 282us/step
12/12 [==============================] - 0s 344us/step
12/12 [==============================] - 0s 267us/step
12/12 [==============================] - 0s 4ms/step
12/12 [==============================] - 0s 337us/step
12/12 [==============================] - 0s 294us/step
12/12 [==============================] - 0s 306us/step
12/12 [==============================] - 0s 278us/step
12/12 [==============================] - 0s 284us/step
12/12 [==============================] - 0s 275us/step
12/12 [==============================] - 0s 277us/step
12/12 [==============================] - 0s 338us/step
12/12 [==============================] - 0s 268us/step
12/12 [==============================] - 0s 277us/step
12/12 [==============================] - 0s 326us/step
12/12 [==============================] - 0s 282us/step
12/12 [==============================] - 0s 260us/step
12/12 [==============================] - 0s 279us/step
12/12 [==============================] - 0s 279us/step
12/12 [==============================] - 0s 287us/step
12/12 [==============================] - 0s 287us/step
12/12 [==============================] - 0s 273us/step
12/12 [==============================] - 0s 264us/step
12/12 [==============================] - 0s 295us/step
12/12 [==============================] - 0s 277us/step
12/12 [==============================] - 0s 263us/step
12/12 [==============================] - 0s 312us/step
12/12 [==============================] - 0s 275us/step
12/12 [==============================] - 0s 268us/step
12/12 [==============================] - 0s 280us/step
12/12 [==============================] - 0s 271us/step

WARNING:matplotlib.backends.backend_ps:The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.